@startuml
class User
{
    -Profile profile
    -boolean isLoggedIn
    +Profile getProfile()
    +boolean getIsLoggedIn()
    +void setIsLoggedIn()
    +void setProfile()
    +void manageCards()
    +void addCardToDeck()
    +void addUserCard(Card[] cardsToBeAdded)
    +void tradeCards(Card cardToBeRemoved)
    +void printDeck()
}
class Profile
{
    -String username
    -String password
    -int coins = 20
    -int eloPoints = 100
    -Card[] stack
    +Profile(String un, String pw)
    +void setUsername(String name)
    +void setPassword(String pw)
    +void setCoins()
    +void setEloPoints()
    +String getUsername()
    +String getPassword()
    +int getCoins()
    +int getEloPoints()
    +Card[] getUserCards()
    +void printProfile()
}
enum Result
{
    LOSS
    WIN
    TIE
}
class Package
{
    +{static} final int cardCount = 5
    -Card[] cards
    +Card[] chooseRandomCards()
}
class Card
{
    -String name
    +int final damage
    -byte final elementType
    -boolean isInDeck
    +int getCardName()
    +byte getElementType()
    +boolean getIsCardInDeck()
    +void setCardName()
    +void setElementType()
    +void setCardInDeck()
}
class CardMonster
{
    +void makeDamage()
}
class CardSpell
{
    +void makeDamage()
}
class Battle
{
    -User userOne
    -User userTwo
    +void setUsers(User firstUser, User secondUser)
    +User getUserOne()
    +User getUserTwo()
    +void printInstructions()
    +void printBattleInformation()
    +void showBattleMenu()
    +void startNewBattle()
    +void endOfBattle()
    +void shop()
    +void setNewEloPoints()
}
class Game
{
    -User users[]
    -Statistics stats
    +void startGame()
    +void showMenu()
    +void startBattle()
    +void viewEditProfile()
    +void endGame()
    +void signIn()
    +boolean signUp()
    +boolean login()
    +void printAsciiImage()
    +void printWelcomeImage()
    +void printInstructions(boolean inputError)
    +{static} void clearScreen()
}
class Statistics
{
    +void printGameStats()
    +void printBattleStats(int battleId)
}
class Database
{
    +boolean registerUser(String username, String password)
    +boolean loginUser(String username, String password)
}

CardMonster <|-- Card
CardSpell <|-- Card
User "1" o-- "0..*" Card : "owns"
Game "1" *-- "0..*" Battle : "take place"
Game "1" *-- "1" Statistics : "has"
Game "1" *-- "2" User : "has"
Package o-- "1..*" Card : "contains"
Battle "1..*" *-- "2" User : "is battled"
Result "1" *-- "1..*" Battle : "ends in"
Statistics "1" o-- "1..*" User : "make"
Profile "1" *-- "1" User : "has"
@enduml