@startuml
class User
{
    -Profile profile
    +void manageCards()
    +void addCardToDeck()
    +void addUserCard(Card[] cardsToBeAdded)
    +void printDeck()
}
class Profile
{
    -String username
    -String password
    -int coins = 20
    -int eloPoints = 100
    -Card[] stack
    +Profile(String un, String pw)
    +void printProfile()
}
enum Result
{
    LOSS
    WIN
    TIE
}
enum ElementType
{
    FIRE
    WATER
    NORMAL
    NONE
}
class Card
{
    -String name
    +int final damage
    -boolean isInDeck
    -ElementType type
}
class Battle
{
    -User userOne
    -User userTwo
    +void setUsers(User firstUser, User secondUser)
    +void printInstructions()
    +void printBattleInformation()
    +void showBattleMenu()
    +void startNewBattle()
    +void endOfBattle()
    +void setNewEloPoints()
}
class Shop
{
    +{static} final int cardCount = 5
    +void purchaseCards()
    +void tradeCards(Card cardToBeRemoved)
    +void shopMenu()
    +void printInstructions(boolean wrongInputMade)
}
class Game
{
    -User users[]
    -Shop shop
    +void startGame()
    +void showMenu()
    +void startBattle()
}

User "1" o-- "0..*" Card : "owns"
Game "1" *-- "0..*" Battle : "take place"
Game "1" *-- "2" User : "has"
Battle "1..*" *-- "2" User : "is battled"
Result "1" *-- "1..*" Battle : "ends in"
Profile "1" *-- "1" User : "has"
Shop "1" o-- "1..*" User : "buys Cards"
Shop "1" o-- "1..*" Card : "sells"
Game "1" *-- "1" Shop : "has"
ElementType "1" *-- "0..*" Card : "is"
@enduml